In [1]:
[[123,66,12],[111,99,40],[10,90,100]]

[[123, 66, 12], [111, 99, 40], [10, 90, 100]]

In [5]:
import numpy
n = numpy.arange(27)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [6]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [7]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
import cv2

In [18]:
gray_img = cv2.imread('smallgray.png',0)
gray_img

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
print(gray_img)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [20]:
gray_img[2,3]

97

In [21]:
gray_img[2,4]

182

In [24]:
for i in gray_img:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [25]:
gray_img[:,2]

array([104, 255, 255], dtype=uint8)

In [26]:
print(gray_img[:,2])

[104 255 255]


In [27]:
for i in gray_img.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [28]:
for i in gray_img.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [29]:
hzntl_array = numpy.hstack((gray_img,gray_img))

In [30]:
hzntl_array

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
vert_array = numpy.vstack((gray_img,gray_img))

In [32]:
vert_array

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [33]:
three_hstack_array = numpy.hstack((gray_img, gray_img, gray_img))

In [35]:
print(three_hstack_array)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [36]:
h_split = numpy.hsplit(gray_img, 5)

In [37]:
h_split

[array([[187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182]], dtype=uint8)]